server:
  port: '${server.port}'
  error:
    include-stacktrace: ALWAYS

management:
  server:
    port: ${management.port}
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: ${project.name}
  output:
    ansi:
      enabled: always
