name: Deploy Docker Image

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
  push:
    branches:
      - 'rc/**'

jobs:
  build-and-deploy:
    uses: valitydev/java-workflow/.github/workflows/maven-service-deploy.yml@v3
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
